server:
  port: 8063 #Tomcat端口

#  //日志级别
#  dubbo.protocol.parameters.loglevel=8
#  //日志路径
#  dubbo.protocol.parameters.accesslogpath=./logs/provider
#  //provider使用的拦截器
#  dubbo.provider.filter=providerLog

dubbo:
  application:
    name:  springboot-dubbo-consumer-demo
    qos-enable: true  # Qos（Quality of Service）是Dubbo的在线运维命令，可以对服务进行动态的配置、控制及查询，Dubboo2.5.8新版本重构了telnet（telnet是从Dubbo2.0.5开始支持的）模块，提供了新的telnet命令支持，新版本的telnet端口与dubbo协议的端口是不同的端口，默认为22222
    qos-port: 33333
    qos-accept-foreign-ip: false
  registry:
    address: zookeeper://localhost #zookeeper地址
    port: 2181 #提供注册的端口
    # 读者请换成自己的zookeeperip
    protocol: zookeeper
    check: false
  monitor:
    protocol: register
  consumer:
    check:  false
    timeout: 3000
#    filter: consumerTraceId   #consumer使用的拦截器

#bpm域名过滤
bpm:
  fiter:
    #domain: http://xxx.sit,https://xxxxx.net:8089,http://xxxxx.sit:8088,http://xxxxx:8888,https://xxxxx:8443
    domain: http://localhost:8063




